mail_driver = maildir
mail_path = /mail
mailbox_list_layout = fs
mail_inbox_path = /mail/INBOX

namespace inbox {
  inbox = yes
}

mail_privileged_group = mail

mail_cache_fields = hdr.date hdr.subject hdr.from hdr.sender hdr.reply-to hdr.to hdr.cc hdr.bcc hdr.in-reply-to hdr.message-id imap.bodystructure mime.parts body.snippet
mail_always_cache_fields = hdr.date hdr.subject hdr.from hdr.to hdr.cc hdr.message-id body.snippet imap.bodystructure
mail_never_cache_fields = imap.envelope
