default_vsz_limit = 8192M
service imap-login {
  inet_listener imaps {
#    port = 993
#    ssl = yes
  }
}
service imap {
  # no settings
}
service auth {
  unix_listener auth-userdb {
    mode = 0666
  }
}
