mail_plugins = fts fts_solr virtual

fts solr {
  fts_solr_url = http://solr:8983/solr/dovecot/
}

language en {
  default = yes
  language_filters = lowercase snowball stopwords
  language_tokenizers = generic email-address
}

fts_autoindex = yes
fts_search_read_fallback = no

fts_decoder_driver = tika
fts_decoder_tika_url = http://tika:9998/tika/

fts_search_add_missing = yes
fts_driver = solr
